### ISSUE TITLE
Xrm PowerShell Provider

### ISSUE THREAD

**Issue by RStadlmair** [seanmcne/Microsoft.Xrm.Data.PowerShell#149]
Hi all !

Have there ever been thoughts to write a Xrm Provider ?
Would be cool to do:
_cd Xrm:\OrgName\Accounts
Get-Childitem_

or similar.

Thanks / Roman

**Comment by seanmcne** [comment]
That's an interesting idea, my initial thought is that it could simply translate to webAPI calls as the format is quite similar.  I'll do some research on how to implement it and see if we'd go about creating a new project and/or repo for something like this.

**Comment by RStadlmair** [comment]
Hi Sean !
Did your research lead to a decision ?
R.

**Comment by amervitz** [comment]
@RStadlmair, do you have a situation in mind for when this would be used? I foresee some limitations and hurdles to using one effectively, including:

- It appears you can't copy objects between PowerShell providers [(source)](https://social.technet.microsoft.com/Forums/en-US/38f33f00-f924-456b-8aa4-fee811ad5eae/custom-powershell-provider-and-copyitem-between-logical-file-system-providers?forum=winserverpowershell). If you could though, it would be interesting to be able to copy/sync records between CRM instances but this could get complicated to do properly
- I imagine you'd end up with a single-level flat hierarchy based on entity names, and would then have a hard time navigating or finding records because you'd be dealing with hundreds or thousands at a time that would be hard to identify if listed based on their IDs, which I think you'd need because CRM doesn't enforce unique record names

**Comment by RStadlmair** [comment]
@amervitz: Dealing with crmdata needs always planning regarding what to extract, what properties and then a subsequent selection, to have a nice, easily readable Format for reporting and other further processing
My thought was a provider could do this work for me and i could only do something like:
```
Set-Location Accounts
Get-Childitem 'Con*'
```
On the other hand you are right, the flat structure is a Problem, beginning from a certain amount of data.
R.

**Comment by RStadlmair** [comment]
This Project 
[https://github.com/JozsefHorvath/DynamicsCRM-Automation](https://github.com/JozsefHorvath/DynamicsCRM-Automation)

has a CRM Provider by the way.
Just experimenting with it !

**Comment by seanmcne** [comment]
Thanks for the discussion, I've looked at it a bit but haven't mocked anything up at this point.  On one hand the provider concept makes some sense, on the other hand the way CRM works it could get quite complicated.  If there were some kind of semi-generic oData provider - that would probably work best.  That said, PowerBi desktop is basically a generic oData explorer and the same hurdles we have in that UI when stitching the data together would probably exist in this as well.  

If the scope were to be somewhat limited this could be something relatively simple, but for the more complicated deployments, record types, data types, etc - it may get complicated.

**Comment by seanmcne** [comment]
Hey @RStadlmair / Roman - thanks for the reference, this would be possible but unfortunately I don't think it's going to be in scope at this point in time.  As the REST Endpoint continues to mature and XrmTooling continues to advance it may be possible but I think it may require some processing that would be much better suited for a C# code based module.  I think I'm going to close this for now, but I appreciate the input and I think the idea is a solid one - I just don't think we'll have the time (at this point at least) to pull this off (doesn't mean that won't change though).
