### ISSUE TITLE
Add .ToEntityReference() to CrmRecords - OR (see comments)

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#152]
Add a .ToEntityReference() to returned CRM Records - then you can do something like the following - which avoids confusion. 

$Customer = get-CrmRecord -EntityLogicalName account -Id "be67fbd5-664f-e611-80ea-5065f38b4121" -Fields \* 

$ChildCustomer = New-CrmRecord -EntityLogicalName account @{"name"="child account name";"parentaccountid"=$Customer.ToEntityReference()}

Another option is if the value for a lookup field is a Guid string or Guid value we could automatically convert these properties to EntityReferences (this would involve metadata work and could introduce more problems).

**Comment by kenakamu** [comment]
I do not want to have any () functions in PowerShell, so let me script CrmRecord object for reference rather than toEntotyReference function. How do you think?

**Comment by amervitz** [comment]
@kenakamu,

Microsoft.Xrm.Sdk already contains a ToEntityReference() method, so it would be somewhat natural for those who've used the Entity class API to have a function on the returned objects that achieves the same result, see [Entity.ToEntityReference Method ()](https://msdn.microsoft.com/en-us/library/microsoft.xrm.sdk.entity.toentityreference.aspx).

What would the end result be with this change you mention?

> let me script CrmRecord object for reference rather than toEntotyReference function

Would it for example result in something like this after performing a Fetch XML query?

`$result.CrmRecords[0].EntityReference`

If added as note property, would the Set-CrmRecord logic need extra logic to ignore the added EntityReference note property when enumerating the fields to save back to CRM?

**Comment by seanmcne** [comment]
@kenakamu can we look at how we could just have the function interpret the object and create the entity reference if applicable? Then if object in the variable is of a Crm Record type then it would just know how to handle it.  

Ultimately, this may be a design limitation of our project right now since we're using entirely custom objects with note properties - I'd be curious to know from a design standpoint are we better off creating custom types that align to CRM Types, at least for Entity?   I could see some advantages to this, we could have Entity.Id instead of Entity.<entityname>Id, etc.  Should we be looking at custom types for Entity @kenakamu?

**Comment by amervitz** [comment]
A decision on this would be beneficial for #151 because I'm finding the grant, revoke, and modify access requests primarily deal with entity references. I could prototype something for this at the same and we could see what works in practice.

**Comment by seanmcne** [comment]
How about a Convert-ToCrmEntityReference?  

@kenakamu - what are your thoughts on constructing an actual CRM Entity type versus the generic type used today that makes it difficult to identify if the object is an entity or not?

**Comment by kenakamu** [comment]
I am not sure about using Entity type as we have better control of generic type. Need to discuss more detail in separate thread.

**Comment by amervitz** [comment]
I like the idea of either `ConvertTo-CrmEntityReference` or extending `New-CrmEntityReference` with a new `-CrmRecord` parameter (and ParameterSetName), to accept a CrmRecord PSObject and return an [EntityReference] object. Usage of either one, with `New-CrmEntityReference` as an example, would then look like this:

`$contactRef = New-CrmEntityReference -CrmRecord $contact`

CrmRecord could be a ValueFromPipeline parameter as well to support pipeline scenarios like the following with the `Invoke-CrmAction` function I'm working on when dealing with a bound action:

`Get-CrmRecords <parameters> | New-CrmEntityReference | Invoke-CrmAction <parameters>`

Another thing that I think would be useful for this and other functions that accept a CrmRecord is to start adding a PSTypeName to the PSObject that is created and returned by the various *-CrmRecord* functions. Then the PSTypeName attribute could be included in function parameters to restrict which objects can be assigned to the -CrmRecord parameter instead of accepting any PSObject. A proprosed PSTypeName to use would be `Microsoft.Xrm.Data.PowerShell.CrmRecord`.

**Comment by seanmcne** [comment]
@kenakamu curious why you're against attaching a toEntityReference() method to returned entity objects?

**Comment by kenakamu** [comment]
I am not against t but I prefer keep the powershell way rather than c# way :)

**Comment by kenakamu** [comment]
So what shall we do here? Add a method or give new param for New-CrmEntityReference -crmrecord?

**Comment by seanmcne** [comment]
I think I found a somewhat elegant way to handle this - there's a bug in the result info where we're getting back a "ReturnProperty_Id " with a space so I had to put defensive code in to try and trim the whitespace to avoid confusion.

**Comment by kenakamu** [comment]
done by @seanmcne
