### ISSUE TITLE
How to use Get-CrmRecord with -ErrorAction Ignore

### ISSUE THREAD

**Issue by amervitz** [seanmcne/Microsoft.Xrm.Data.PowerShell#162]
I'm trying to use Get-CrmRecord with the -ErrorAction Ignore action preference so that if the record doesn't exist, the returned value will be null.

For example, this query would never return a result:

`$bu = Get-CrmRecord -conn $conn -EntityLogicalName businessunit -Id ([Guid]::Empty) -Fields name,businessunitid -ErrorAction Ignore`

However when I do this I get the following error:

> The value Ignore is not supported for an ActionPreference variable. The provided value should be used
> only as a value for a preference parameter, and has been replaced by the default value. For more 
> information, see the Help topic, "about_Preference_Variables."
> At C:\Users\amervitz\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.4\Microsoft.Xrm.Data.Powershell.psm1:335 char:9
>          throw $conn.LastCrmException
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : OperationStopped: (:) [], NotSupportedException
>      FullyQualifiedErrorId : System.NotSupportedException

Is this supposed to be a terminating error to be handled by try/catch blocks? Using -ErrorAction Ignore just seemed natural to me.

**Comment by seanmcne** [comment]
At first glance what I'm seeing is that some of the functions need to implement Begin/Process/End for the ErrorAction to function. I can try mocking it up quick, this could represent quite a few changes in the script overall - we'd have to determine if all cmdlet functions need this begin/process/end or if it's just limited to a few.  @kenakamu ?

**Comment by seanmcne** [comment]
FYI I've finally found some kind of documentation eluding to, what is most likely, the issue: 
![image](https://cloud.githubusercontent.com/assets/2292260/21111838/03cde000-c069-11e6-88c0-13d59966e3d0.png)

http://stackoverflow.com/questions/11198023/why-does-an-error-still-show-when-i-specify-erroraction-silentlycontinue 

Today, get-CrmRecord returning null is considered a 'terminating error' because we're throwing it or using write-error.  What I'm not entirely clear on, is if were writing functions like this one - where do we draw the line between a terminating error and non-terminating error.  For instance, if I expect an error when a record doesn't exist I'd want that to terminate the function execution unless I tell it to ignore.  I'm going to reach out to a few folks and see if I can get some clarity on how best to handle this (if there are any best practices today).

**Comment by seanmcne** [comment]
Unfortunately I didn't get any real clarity from the people I've reached out to at this point.  I think as of right now I'd recommend using a trap / try/catch for now.  If you've got some other feedback in how we can better accommodate, it's always appreciated.

**Comment by amervitz** [comment]
My suggestion is to use try/catch statements within the cmdlets (i.e. advanced functions) inside the module, and if an exception occurs, to pass the exception object to Write-Error. This is what I've done in the cmdlets added in PR #163 to pipeline multiple input objects and enable the end user to control through the -ErrorAction switch what happens when an exception occurs when the cmdlets encounter an internal exception on an individual input object.
