### ISSUE TITLE
Online documentation?

### ISSUE THREAD

**Issue by ian-moore** [seanmcne/Microsoft.Xrm.Data.PowerShell#181]
Have there been any plans for online documentation on the included cmdlets? Relying on the ISE for help info can be tedious. It would also show others all commands that are available without needing to install the module.

I tried running [platyPS](https://github.com/PowerShell/platyPS) against the solution and it can generate markdown for a module - might be a nice starting point.

I would be happy to make a pull request with some auto-generated docs but was wondering if there were other thoughts on this topic.

**Comment by seanmcne** [comment]
Hey Ian, 
I don't see why we couldn't fire up a repo or maybe put a folder for the Markdown output - it's another thing to generate for each release which will probably push us to try and invoke more of an automated build process now. 

To be honest I've always been a big user of "get-member"  "get-help | cmdlet" to inspect the cmdlets via powershell, but I also realize that not everyone is probably into Powershell enough to make that efficient. 

Since @kenakamu generates the builds most of the time - do you have any thoughts @kenakamu?

**Comment by kenakamu** [comment]
I will look into integration from VSTS then.

**Comment by seanmcne** [comment]
that may be interesting I've also put quite a bit of time and exploration into using appveyor to publish builds.  I have a test working well now, I'm just dialing in the automatic build #'s and we will have a nearly instant publish to PSGallery and a release here on GitHub.
