### ISSUE TITLE
Pressing Cancel in Get-CRMConnection -InteractiveMode exits the script.

### ISSUE THREAD

**Issue by RIKIKU** [seanmcne/Microsoft.Xrm.Data.PowerShell#209]
It seems that if you use Get-CRMConnection -InteractiveMode and then press Cancel, the whole script exits. 
This isn't great for scenarios where you want to loop through connecting to different environments. It would be better if it threw an error. At least then a Try Catch could be used to handle it.

**Comment by seanmcne** [comment]
My thought is that pressing cancel in the interactive dialog would be akin to pressing cancel (Ctrl+C) in powershell which aborts the script execution. 

For any scripting I would suggest avoiding interactive mode and using something like Connect-CrmOnline -ServerUrl -Credential $cred   so you can avoid an interactive dialog.  Due to the recent update of the 8.2 libraries we now have a connection string variable that will ensure each connection (if you store them in different variables) will truly be isolated rather than acting like a singleton. 

Hope this helps explain.  Thanks!

**Comment by RIKIKU** [comment]
Indeed it does behave in the same way as CTRL+C. It is odd behaviour though as it is not consistent with the rest of the interactive PowerShell cmdlets. Get-Credential is a good example of how it does not kill the script if the user presses cancel on the dialog.  I've since realised that this repo is not where the Get-CRMConnection Cmdlet was created, so I think I am barking up the wrong tree here anyway.
I'll try my luck on the Microsoft Connect page, see how that goes. Thanks for the reply!

**Comment by seanmcne** [comment]
Ah I see where you're coming from, for feedback on xrm tooling log it at https://ala.ms/crmideas

**Comment by RIKIKU** [comment]
Thanks Sean,
I managed to find it and logged my request over there.
 For reference: https://ideas.dynamics.com/ideas/dynamics-crm/ID0001499
