### ISSUE TITLE
Delegated Admin Acceptance for Multiple Tentants 

### ISSUE THREAD

**Issue by Frosty3** [seanmcne/Microsoft.Xrm.Data.PowerShell#220]
Hi All,

I'm fairly new to PS and recently start moving my customers microsoft accounts to a CSP provider. I have to login with each customers admin credentials to accept this relationship and it is very time consuming. I'm having trouble getting started with the PS script that would allow me to do this for all of my customers from my partner portal in O365.

Any thoughts?

**Comment by seanmcne** [comment]
Please take a look @ this bug, when the next major release of the sdk ships we should be able to start enabling you to do this - I'm looking forward to it because I can see a large need for this in our CSP provider/partner community (as well as B2B).  https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/issues?q=is%3Aissue+is%3Aopen+csp+label%3ABLOCKED

**Comment by seanmcne** [comment]
Ref: #193
