### ISSUE TITLE
Export / Import CRM Data Encryption Key via script

### ISSUE THREAD

**Issue by PvilleStang** [seanmcne/Microsoft.Xrm.Data.PowerShell#244]
Is there a way to query / change the CRM Data Encryption key from Powershell?

Tried searching this one, and keep running into the same solutions: log in via GUI and show key, copy / paste / save for later use.

We're currently running a CRM training environment that our training staff want to revert nightly to a clean build.  Currently, our DBAs are restoring the DB snapshot onto a running CRM org, but we've told them to cease this since it corrupts the MSCRM_Config DB.  The solution I'm coming up with disables / deletes the org, restores the DB snapshot, then imports the DB as a new org (with the same name as before).  The only piece missing is a way to automate the encryption key insert.  This will be a nightly scheduled task after hours, and would like to be able to set it and forget it.

**Comment by seanmcne** [comment]
```powershell
$IsActiveReq = New-Object Microsoft.Xrm.Sdk.Messages.IsDataEncryptionActiveRequest
$conn.ExecuteCrmOrganizationRequest($IsActiveReq)
$SetReq = New-Object Microsoft.Xrm.Sdk.Messages.SetDataEncryptionKeyRequest
$SetReq.ChangeEncryptionKey=$true
$SetReq.EncryptionKey="###############################################"
$conn.ExecuteCrmOrganizationRequest($SetReq)
```
You can use a similar approach with the following requests: 
- IsDataEncryptionActiveRequest: Checks if data encryption is currently running (active or inactive).
- RetrieveDataEncryptionKeyRequest: Retrieves the data encryption key value.
- SetDataEncryptionKeyRequest: Sets or restores the data encryption key. To prevent accidentally running multiple change requests in parallel, this SDK message will be throttled so that only one request can run at a time.


As for the restore you can definitely do this - however, you should use powershell or a console app to:
- Use the deployment powershell library (or Deployment webservices) to disable the crm instance 
- drop the db or restore over the top 
- Use the deployment powershell library (or Deployment webservices) to import the CRM instance back into the deployment (import org) you can use auto mapping or an existing mapping file, etc. 

This is fully supported and won't hose the mscrm_config db.

**Comment by PvilleStang** [comment]
That is awesome, but only one issue after testing.  When querying if Data Encryption is active upon import, it is of course inactive, so it will not "change" the key, rather it takes the input, but remains inactive on the Data Encryption side.  How can I go about flipping the encryption to Active at that point?

**Comment by seanmcne** [comment]
When you execute a "SetDataEncryptionKeyRequest" does it not activate the key?  

For instance: 
```powershell
$setKey = New-Object Microsoft.Xrm.Sdk.Messages.SetDataEncryptionKeyRequest
$setKey.EncryptionKey = $keyValue;
$conn.ExecuteCrmOrganizationRequest(rSetKey); 
```

To change an already active key you would set both the keyvalue and ChangeKey = $true.  I was under the impression that by not touching the ChangeKey property and just setting the key it would set it and activate it.

**Comment by PvilleStang** [comment]
Your final comment was spot on, forgot to notate it was the solution to the issue.

**Comment by seanmcne** [comment]
Be sure to also check out Sanjin's great and much simpler solution to invoking this operation here: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/master/Microsoft.Xrm.Data.PowerShell.Samples/OrgEncryptionKey/OrgEncryptionKey.ps1
