### ISSUE TITLE
"Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value of type "Microsoft.Xrm.Tooling.Connector.CrmServiceClient" to type - Again HELP

### ISSUE THREAD

**Issue by Atili0** [seanmcne/Microsoft.Xrm.Data.PowerShell#287]
Hi team, 

I quick question. I am trying to pass mine connection parameter from  Connect-CrmOnlineDiscovery -InteractiveMode to custom DLL. 

I am getting the connection object with out problem, but when I try to pass this object as param to me dll i am getting this error

`Get-NetworkAdapter : Cannot bind parameter 'Connection'. Cannot convert the "Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value of type "Microsoft.Xrm.Tooling.Connector.CrmServiceClient" to type
"Microsoft.Xrm.Tooling.Connector.CrmServiceClient".
At line:13 char:32
Get-NetworkAdapter -Connection $conn
     CategoryInfo          : InvalidArgument: (:) [Get-NetworkAdapter], ParameterBindingException
     FullyQualifiedErrorId : CannotConvertArgumentNoMessage,PowerShellModuleCSharp.GetNetworkAdapterCmdlet`

I have the same library in both project ( i have the version [2.7.2 of XRM.DATA](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/releases) ) and version 9 of Dynamics DLL.  #27

**Comment by seanmcne** [comment]
Since the objects in PowerShell are just objects of their respective types I would expect you to be able to write a cmdlet that would find and interact with $conn of type Microsoft.Xrm.Tooling.Connector.CrmServiceClient - as long as the types match.  I assume the custom dll is it's own module that's trying to accept a type of the CrmServiceClient? 

You could also see if your cmdlet could find the global $conn variable as well since that should be available at the time as well.
