### ISSUE TITLE
Automating connection object creation without PSCredentials

### ISSUE THREAD

**Issue by zugnush** [seanmcne/Microsoft.Xrm.Data.PowerShell#291]
Great tool.

I can create a connection using 
`Connect-CrmOnPremDiscovery -InteractiveMode`
without completing the User Name, Password, Domain fields, by just clicking "login".

I don't understand the Windows authentication magic but it works.

I'd like to use this in an automated job, without calling Get-Credential

Is it a Windows security limitation that there is no way to default credentials in the non interactive version, or is there a way to mimic the Interactive behaviour without the dialog?

**Comment by seanmcne** [comment]
@zugnush the connection is established via the XRM Tooling component provided by Microsoft.  Unfortunately it looks like they explicitly block auto windows auth via default credentials (I would assume this is a security enhancement to force you to acknowledge the login rather than it just magically logging you in via a script).  

There might be a bit of a hack you could try by instantiating your own CRM Service Client using windows auth but I'm not sure where the default credentials block is taking place and if that would allow you to circumvent it.  Meaning, you could look at creating your own instance of a CrmServiceClient and assigning it to a variable (such as $conn).  

I'm hoping that we'll get an option to use a secret or certificate identity instead - also feel free to log feedback specifically for XRMTooling - https://aka.ms/crmideas 

Finally, you can always store a secure string using a key or encrypted by your local user key.  If you're using azure automation you can save secure variables and if you have access to a keyvault you can also store your secret or password there and retrieve it via powershell.
