### ISSUE TITLE
Add-CrmSecurityRoleToTeam and Add-CrmSecurityRoleToUser should support the roleName

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#3]
Add support for the Role name (case insensitive), the function should find the user, identify the user, then find the role in that BU and associate it.

**Comment by kenakamu** [comment]
The functions has CrmRecords sets and ID sets, but do you want to have Name sets? just curious what if they want to assign multiple users to a role and in this case, user ids and role name are passed.

Instead of adding more parameters, how about adding example to make it easier for users?

$user = (Get-CrmRecords -conn $conn -EntityLogicalName systemuser -FilterAttribute fullname -FilterOperator eq -FilterValue "kenichiro nakamura" -Fields systemuserid,businessunitid).CrmRecords[0]
$roles = (Get-CrmRecords -conn $conn -EntityLogicalName role -FilterAttribute name -FilterOperator eq -FilterValue "salesperson" -Fields roleid,businessunitid).CrmRecords
$role = $roles | ? {$_.businessunitid -eq $user.businessunitid}
Add-CrmSecurityRoleToUser $user $role

Now when I write this sample, it seems a bit complicated. What parameter we should add. Just support $RoleName?

**Comment by kenakamu** [comment]
Updated functions. Please see pull request

**Comment by kenakamu** [comment]
Done
