### ISSUE TITLE
Enable-CrmLanguagePack Error 

### ISSUE THREAD

**Issue by ArtKarp** [seanmcne/Microsoft.Xrm.Data.PowerShell#323]
When I run the script to enable a language pack with D365 Online Version 1710 (9.0.2.1470) I get the following error.  However, when I check the enabled language packs within the org, it is enabled. I am trying to enable multiple language packs in a row within a test org.  After the first language failure the script stops.

Updated to the current version of Microsoft.XRM.Data.PowerShell prior to running the command. 
(Got the same error on an earlier version too)

My Connection:
-------------------------------------------------
$username = "MYUSERNAME"
$password = "MYPASSWORD"

$secstr = New-Object -TypeName System.Security.SecureString
$password.ToCharArray() | ForEach-Object {$secstr.AppendChar($_)}
$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $secstr
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12

$Conn = Get-CrmConnection  -OrganizationName $OrgName -DeploymentRegion NorthAmerica -OnLineType Office365  -Credential $cred  -MaxCrmConnectionTimeOutMinutes 20

The Error Message: 
------------------------------------------------------
Enable-CrmLanguagePack -conn $conn -LCID 3082 #Spanish

The remote server returned an unexpected response: (502) Bad Gateway.
At C:\Users\-MYUSERNAME-\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Data.Powershell.psm1:2578 char:9
+         throw $conn.LastCrmException
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ProtocolException
    + FullyQualifiedErrorId : The remote server returned an unexpected response: (502) Bad Gateway.

**Comment by seanmcne** [comment]
This is related to an infrastructure related outage going on for some instances - I think it was mainly in the EMEA/EU region but you can try again and if it persists you could open a support ticket (though they are aware of the issue and have been working on fixing it today).  Specifically, the issue is the hosted service has Intermittently returning 502 bad gateway.

**Comment by ArtKarp** [comment]
That's strange.  The orgs I am testing on are all located in the North America region.  

I retested this today (Sep. 12, 2018 5:30 PM Pacific time) and it and after an hour I got the error below and the language did not install.  

It is interesting that the error has the same line number and char as the gateway error previously. 

Error Message: 

The request channel timed out while waiting for a reply after 00:59:59.9989984. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this 
operation may have been a portion of a longer timeout.
At C:\Users\art.karp\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\Microsoft.Xrm.Data.Powershell.psm1:2578 char:9
+         throw $conn.LastCrmException
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], TimeoutException
    + FullyQualifiedErrorId : The request channel timed out while waiting for a reply after 00:59:59.9989984. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The 
    time allotted to this operation may have been a portion of a longer timeout.

**Comment by seanmcne** [comment]
I suggest broadening your timeout upwards of a couple minutes (5 his historically the maximum time you can get away with).  We had a similar issue in #299 and I think this operation just (sometimes) takes a very long time to execute. 

The underlying sdk message we're executing is just a very simple: Microsoft.Crm.Sdk.Messages.ProvisionLanguageRequest 

https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/6c03fcf391d0fd9cdb8b2312a8d33ba90b4c2f84/Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1#L2593

**Comment by seanmcne** [comment]
Thanks for the reply - normally I'd suggest using connect-crmonline -serverurl <orgurl> for consistency and then setting the timeout though it should roughly be the same - you never know with crmserviceclient how it's going to connect based on the parameters :|  Either way, I don't think that's the underlying problem. 

I've seen this before and usually a second try can enable the language pack or the operation will continue in the background and eventually complete - I'm not sure why the PG has this as synchronous if it can take so long.  It seems like other ways of enabling language packs use async requests instead (which I'm not sure if we can do from an SDK point of view or not at this point).  Can you see if the language pack eventually did get enabled or what happens if you run it a second time?

**Comment by ArtKarp** [comment]
I tried using Connect-CrmOnline.  I got the connection to work after figuring out why the example in the help file doesn't work.  :(    It shows "-Url".  It should be "-ServerUrl". 

Current Example:
PS C:\> Connect-CrmOnline -Credential (Get-Credential) -Url "https://contoso.crm.dynamics.com"

Fixed Example:
PS C:\> Connect-CrmOnline -Credential (Get-Credential) -ServerUrl "https://contoso.crm.dynamics.com"

Once I ran it, I got the 2 min timeout error you mentioned.  However, I don't see a parameter that lets you increase the timeout.  It doesn't have "-MaxCrmConnectionTimeOutMinutes" like Get-CrmConnection does.  How would I increase the timeout minutes?

Even with the error, the language pack was installed.  If I can get the timeout working, that would be great for setting up new test orgs that require that multiple languages be enabled.

**Comment by seanmcne** [comment]
Hi Art, 
Yes there is an underlying network timeout that you need to contend with, usually it's after 5 minutes.  From what I've heard and seen, these language pack operations tend to either complete very quickly or take a very long time and may ultimately succeed after some time.  It looks like these request types are baked into the connector & sdk as "synchronous" calls and unfortunately will make you wait for a response (which is at odds with our services network timeout if it exceeds).  

I'm sorry you're still running into issues, since this is an underlying sdk message it's out of this projects control to find another method to enable language packs. You could open a support case to help surface it to the support and product team so it's on the radar to get updated in the future at some point.  Thanks for taking the time to investigate and reach out, I hope other aspects of the module & sdk are working better than this Out of Box SDK message to enable language packs.

**Comment by seanmcne** [comment]
Please see #421
