### ISSUE TITLE
How can I setup a hierarchy via powershell 

### ISSUE THREAD

**Issue by mwolfaardt** [seanmcne/Microsoft.Xrm.Data.PowerShell#348]
I would like to setup a self referencing hierarchy via powershell in order to showcase org structure.

**Comment by mwolfaardt** [comment]
Any update on my ask?

**Comment by tyler-hogsett-microsoft** [comment]
Currently, the Microsoft.Xrm.Data.Powershell does not have any functionality around managing metadata, so in order to create relationships programmatically, you'll need to use the approach described in the [documentation](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/org-service/sample-create-retrieve-entity-relationships#example). This is, however, possible in PowerShell with the use of [using](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_using?view=powershell-6) statements to import the required C# classes.

However, [hierarchy rules](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/entities/hierarchyrule) work like any other entity, so you can use this PowerShell module to create those. In the sample code below, after creating the one-to-many relationship, I use the module to retrieve a quick view form by its name and then use its guid to create a hierarchy rule:

```
using namespace Microsoft.Xrm.Sdk
using namespace Microsoft.Xrm.Sdk.Messages
using namespace Microsoft.Xrm.Sdk.Metadata

$connection = Get-CrmConnection -Interactive

$request = New-Object CreateOneToManyRequest -Property @{
	OneToManyRelationship = New-Object OneToManyRelationshipMetadata -Property @{
		ReferencedEntity = "contact"
        ReferencingEntity = "contact"
        SchemaName = "new_contact_contact_managerid"
		IsHierarchical = $true
        AssociatedMenuConfiguration = New-Object AssociatedMenuConfiguration -Property @{
            Behavior = [AssociatedMenuBehavior]::UseLabel
            Group = [AssociatedMenuGroup]::Details
            Label = New-Object Label @("Manager", 1033)
            Order = 10000
        }
        CascadeConfiguration = New-Object CascadeConfiguration -Property @{
            Assign = [CascadeType]::NoCascade
            Delete = [CascadeType]::RemoveLink
            Merge = [CascadeType]::NoCascade
            Reparent = [CascadeType]::NoCascade
            Share = [CascadeType]::NoCascade
            Unshare = [CascadeType]::NoCascade
        }
	}
	Lookup = New-Object LookupAttributeMetadata -Property @{
        SchemaName = "new_managerid"
        DisplayName = New-Object Label @("Manager", 1033)
        RequiredLevel = New-Object AttributeRequiredLevelManagedProperty @([AttributeRequiredLevel]::None)
        Description = New-Object Label @("The contact's manager", 1033)
    }
}

$connection.Execute($request)

$quickFormId = (Get-CrmRecords `
	-conn $connection `
	-EntityLogicalName systemform `
	-FilterAttribute name `
	-FilterOperator eq `
	-FilterValue "Contact Quick Form" `
	-Fields @( "formid" ) `
	-TopCount 1
	).CrmRecords.formid

New-CrmRecord `
	-conn $connection `
	-EntityLogicalName hierarchyrule `
	-Fields @{
		name = "new_contact_manager"
		primaryentityformid = $quickFormId
		primaryentitylogicalname = "contact"
	}

Publish-CrmAllCustomization -conn $connection
```

@seanmcne What do you think about adding functionality for managing metadata? Considering how much it takes to manipulate metadata programmatically (e.g. number of parameters), if developers want to manage metadata using PowerShell, it might be best to use the approach shown here instead.

**Comment by seanmcne** [comment]
Hey all, if you want to contribute to the sample repo or add metadata functions, please feel free to send the code along as PR's and we can take a look at them. Thanks! 

PS: added sample: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/master/Microsoft.Xrm.Data.PowerShell.Samples/Metadata/Hierarchies.ps1
