### ISSUE TITLE
Import-crm solutions is not working facing time out issue 

### ISSUE THREAD

**Issue by balakrishna222111** [seanmcne/Microsoft.Xrm.Data.PowerShell#361]
Import-CrmSolution  -conn $CRMConn -SolutionFilePath $importSolutionPath\ -MaxWaitTimeInSeconds 1200 -Debug

this is what i have tried 

1.)some times its importing sometimes doesn't 
2.) i tried with Import-CrmSolutionAsync also

the file size is 6mb

@seanmcne @wangzq @RedsGT @thuld

**Comment by RedsGT** [comment]
If you are setting the timeout value to 20 minutes and the solution import sometimes takes longer then that, what makes you think it's an Xrm.Data.PowerShell issue?  Wouldn't that be an issue with the solution and/or the instance you're importing the solution into?

**Comment by balakrishna222111** [comment]
But some times its importing with in 5 min only @RedsGT

**Comment by RedsGT** [comment]
You'd be better off opening a support case with Microsoft if you can verify that you're seeing this issue with solution inside the UI as well.

**Comment by balakrishna222111** [comment]
From UI i can able to import successfully @RedsGT

**Comment by seanmcne** [comment]
@balakrishna222111 please be aware that the max wait time can't really exceed the timeout configured on the proxy (which the XRM Tooling library defaults to 2 minutes), thought you can try increasing it using Set-CrmConnectionTimeout (though, if you're using sync requests the network connection can only live for so long).  If you use the Async import method that will upload your solution, queue up a job, that job will wait as long as it takes for your solution to import and the cmdlet will constantly poll the job until it hits the max time (a bit of a cheat to let your code yeild while waiting for the import, no matter how long it may take).  That async import job might hit a sql timeout or one other _thing_ that prevents the import but you can always use the async operation id you got back to go query the job and find out why it failed or use the documented script to troubleshoot/analyze all your recent imports (which are also kept in the db). 

For reference here is that troubleshooting script: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/master/Microsoft.Xrm.Data.PowerShell.Samples/Troubleshooting/AnalyzeSolutionImports.ps1 

This script will download your solution imports in recent history and dump the output xml into a folder for you to analyze.  

One other note - just because the synchronous command times out or when the async cmdlet stops polling for updates - that does not indicate anything failed.  Unfortunately, Solution imports are tricky and are heavily dependent on the system not having anything else going on and sql being 100% available and even then, there are sometimes unforseen delays.  The product group has done quite a bit of work to get solution imports more consistent, but there's still some further things to be done around improvement here which is exactly why @RedsGT is suggesting opening a case if you see an actual failure (from those logs produced by the script, for example) so that we can do our best to get that data to the platform team(s) and improve the overal solution import experience. 

Hope this helps!
Sean

**Comment by seanmcne** [comment]
Please see #421
