### ISSUE TITLE
Can not load Module from PowerShell

### ISSUE THREAD

**Issue by leifusc** [seanmcne/Microsoft.Xrm.Data.PowerShell#370]
I downloaded the Microsoft.Xrm.Data.Powershell module from https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/releases/ 
Followed the instructions 
1. Copy the folder to the C:\Windows\System32\WindowsPowerShell\v1.0\Modules folder
2. Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
3. install-module Microsoft.Xrm.Data.PowerShell
However, when I run Connect-CrmOnlineDiscovery -InteractiveMode, I received errors as
Connect-CrmOnlineDiscovery : The 'Connect-CrmOnlineDiscovery' command was found in the module 'Microsoft.Xrm.Data.Powershell', but the module could not be loaded.
For more information, run 'Import-Module Microsoft.Xrm.Data.Powershell'.

Please advise, Thanks in advance!

**Comment by seanmcne** [comment]
This is probably from extracting from a blocked zip (check the install guide for how to unblock before extracting). Otherwise, it is likely easier to download from the PowerShell gallery: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/master/README.md#preferred-install-the-module-via-powershell-gallery
