### ISSUE TITLE
There was an error while trying to deserialize parameter

### ISSUE THREAD

**Issue by ChristopherCarver** [seanmcne/Microsoft.Xrm.Data.PowerShell#386]
The following code fails to create a new record.

`$ref = (Get-CrmRecords -EntityLogicalName account -Fields "*" -TopCount 1 -FilterAttribute name -FilterOperator "eq" -FilterValue "ACME" ).CrmRecords

$ticket = New-CrmRecord -conn $conn -EntityLogicalName incident  -Fields @{"title"="Test from ACME";"customerid"=$ref} `

I have confirmed that the customerid reference is legitimate and contains the proper values. The incident entity is a custom entity made by Provance.

Error Snippet (truncated for brevity):
`FullyQualifiedErrorId : ************ FaultException - Create : incident |=> The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://schemas.microsoft.com/xrm/2011/Contracts/Services:request. The InnerException message was 'Error in line 1 position 8802. Element 'http://schemas.datacontract.org/2004/07/System.Collections.Generic:value' contains data from a type that maps to the name 'System.Collections.Generic:List`1'. The deserializer has no knowledge of any type that maps to this name.`

Google search turns up that setting EnableProxyTypes fixes this issue. https://stackoverflow.com/questions/32179887/crm-2015-sdk-the-deserializer-has-no-knowledge-of-any-type-that-maps-to-this-n

I cannot figure out how to toggle this in the cmdlets.

Thank you for any support and assistance.

**Comment by seanmcne** [comment]
This shouldn't be a proxy types issue since everything in the code is "late bound."  The issue is most likely caused due to $ref not being an EntityReference, $ref is a generic List object containing properties from an "Entity" object (not a reference to an entity) - I added some screenshots showing how we can see the types of the objects. But no worries, in a PR a while back (#235) we added a property called EntityReference which is a shortcut to an EntityReference for the Entity record returned.  It was added for this type of scenario, making references to records a little easier/less complicated.  _Note: an updated script is also below which should hopefully help here._ 

Looking into the type of $ref
![image](https://user-images.githubusercontent.com/2292260/69018425-04d1c700-0972-11ea-8a4e-5e8f6d0233f9.png)

Looking into the type of -> $ref.EntityReference
![image](https://user-images.githubusercontent.com/2292260/69018545-8cb7d100-0972-11ea-9d8a-4b859eb2df1e.png)

```powershell
#note: select all fields isn't ideal if they're not needed
$customer = (Get-CrmRecords -EntityLogicalName account -Fields "name" -TopCount 1 -FilterAttribute name -FilterOperator "eq" -FilterValue "ACME" ).CrmRecords

$ticket = New-CrmRecord -conn $conn -EntityLogicalName incident -Fields @{"title"="Test from ACME";"customerid"=$customer.EntityReference} 
```

**Comment by ChristopherCarver** [comment]
Thank you so much. This explanation fixed the issue. I only have roughly 12 hours experience with Dynamics so far and I have found your tool very helpful in my eBonding endeavors. Please keep up the cause and good work. "We" are counting on you.

**Comment by seanmcne** [comment]
Welcome to the world of PowerApps, Dynamics and the Common Data Service (CDS)!

It’s always a good day to hear the efforts put forth into this project helped save some time 😀
