### ISSUE TITLE
module is not working in a Windows service or Scheduled Task 

### ISSUE THREAD

**Issue by augiaugi** [seanmcne/Microsoft.Xrm.Data.PowerShell#391]
Hello,
I would like to use this module inside a Windows service and its not working.
After open a Microsoft Case they forwarded me to this git repo.

The first issue I had was caused by not enabled TLS1.2 on my server.

> Unable to Login to Dynamics CRMOrganizationWebProxyClient is null

After enable this I am getting the following issue:

> The type 'Microsoft.Xrm.Sdk.Client.IdentityProviderTypeDictionary' is not supported for serialization or deserialization of a dictionary. Keys must be strings.

I can reproduce this issue in an Windows Service (.Net Application that runs Powershell) or in a Scheduled Task.

**Comment by seanmcne** [comment]
Hi, I haven’t tested this scenario. Are you having a windows service start/execute a powershell command for this module?

**Comment by augiaugi** [comment]
Hello, it is not even working in a scheduled task for me and think the root cause is the same.
Here is the test script I am using in the Scheduled Task:

```
try
{
	$Credential = (Import-CliXml "<cred file>").Credential
	Write-Log -Type DEBUG -Message "cred [$($Credential.UserName)]"

	Import-Module Microsoft.Xrm.Data.Powershell | Out-Null
  $CRMConnectionDetails = Connect-CrmOnline -Credential $Credential -ServerUrl '<server>'

  Write-Log -Type DEBUG -Message "CRMConnectionDetails [$(ConvertTo-Json $CRMConnectionDetails -Depth 10 -Compress)]"

  if(!$CRMConnectionDetails.IsReady)
  {
      throw "CRMO login failed for $($Credential.UserName) on server [<server>]"
  }
 
  Write-Log -Type DEBUG -Message "connect success"
}
catch
{
	Write-Log -Type ERROR -Message $_
}
```

and the related log output is:

```
2019.12.02 15:03:29.548;DEBUG;cred [<service_account>]
2019.12.02 15:07:16.814;ERROR;The type 'Microsoft.Xrm.Sdk.Client.IdentityProviderTypeDictionary' is not supported for serialization or deserialization of a dictionary. Keys must be strings.
```

**Comment by augiaugi** [comment]
> "If you’re going to the effort to write/deploy a Windows service it might be worth writing code behind it - if it’s just a task to run you might want to consider using a scheduled task so it’s easier to maintain."

Isnt an option as it is more powerfull than just executing a static script, it is a workflow/task based .NET API Webservice which executes defined Powershell scripts (including dynamic parameter) in order to do tasks on different systems (e.g. AD/Exchange/Exchange Online/SharePoint/CRM Online/....)

**Comment by seanmcne** [comment]
Are you using the same exact user when running your service or the scheduled task? 

![image](https://user-images.githubusercontent.com/2292260/74038559-0f569800-4986-11ea-9feb-621c05f68292.png)

**Comment by augiaugi** [comment]
Yes otherwise i would get a context error on the import

**Comment by seanmcne** [comment]
based on the exceptions and what I've seen, the issue is almost certainly with the decrypting of the credential/password as opposed to the module. 

If I switched to using a method using:System.Security.Cryptography.ProtectedData to store the password it does function properly.  I suspect there's something with the way the user is loaded by a task and/or windows service where it's unable to access credentials in the credential store.  Storing it in a file works this way but it does not use a secure string (the password would be stored as a string in memory as opposed to a secure string). 

I think the most secure way to approach this might be to use certificate auth which involves creating an AzureAD app, uploading a cert for credentials, and storing the cert in a secure store.  Then you can use serviceclient to create a connection.  A second option would be to proceed the way we've explored here using a stored credential but it might take some additional effort to ensure the stored credentials are decryptable under the right circumstances.  

As for cert auth - unfortunately, I've not yet provided a _helper_ to connect using a cert but there are a couple of options we might have to find a way to get this working.  If you're interested in using this approach or already have tried cert auth with online let me know and we'll see if we can get that working in an easier way. 


Here is the test script I used to prove out the credential issue: 

``` powershell
#https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.protecteddata?view=netframework-4.8
#from:https://blag.nullteilerfrei.de/2018/01/05/powershell-dpapi-script/

$filename = "c:\users\username\crypto.txt"
[void] [Reflection.Assembly]::LoadWithPartialName("System.Security")
$scope = [System.Security.Cryptography.DataProtectionScope]::CurrentUser

#store the secret in a file using System.Security.Cryptography.ProtectedData interactively
#as the same user account running the task
#  $plaintext = [System.Text.UTF8Encoding]::UTF8.GetBytes("somepassword")
#  $ciphertext = [System.Security.Cryptography.ProtectedData]::Protect($plaintext, $null, $scope )  
#  [System.Convert]::ToBase64String($ciphertext) > $filename


#read the secret - this uses a unsecured string - to store the value until it creates the cred
#should see if there's an unprotect method or ProtectedData method which would allow reading into a securestring
  $data = Get-Content $filename
  $ciphertext = [System.Convert]::FromBase64String($data)
  $secureString = ConvertTo-SecureString ([System.Text.UTF8Encoding]::UTF8.GetString([System.Security.Cryptography.ProtectedData]::Unprotect($ciphertext, $null, $scope )) ) -AsPlainText -Force
  $Cred = New-Object System.Management.Automation.PSCredential ("user@somedomain.onmicrosoft.com", $secureString)

try
{
     Write-Output "cred [$($Cred.UserName)]"
     Import-Module Microsoft.Xrm.Data.Powershell | Out-Null
    Connect-CrmOnline -Credential $Cred -ServerUrl env.crm.dynamics.com -ForceOAuth -Verbose
    #Write-output "CRMConnectionDetails [$(ConvertTo-Json $conn -Depth 10 -Compress)]"
    Invoke-CrmWhoAmI | out-file "C:\users\username\test.txt" -Append

  if(!$conn.IsReady)
  {
      throw "login failed for $($Cred.UserName)"
  }
 
  "connect success"| Out-File -FilePath "c:\users\username\test.txt" -Append
}
catch
{
	Write-output $_ | Out-File -FilePath "c:\users\username\test.txt" -Append
}
```

**Comment by augiaugi** [comment]
I will it a try on Monday :)

**Comment by seanmcne** [comment]
Just checking in, hopefully you got it working!
