### ISSUE TITLE
Change Settings for "Area that display this Entity" 

### ISSUE THREAD

**Issue by Dolph-Dragon** [seanmcne/Microsoft.Xrm.Data.PowerShell#424]
Hi,

I am trying to find a way to change the settings of an entity that define where the entity will be displayed. 
If you open the settings for an entity you find checkboxes for the ares where the Entity will be displayed. The checkboxes are located in the Section called "Areas that display this entity".

As far as i understand you have to change the SiteMap XML to change the area, where an entity should be placed. It looks kinda complex to check or uncheck those checkboxes via powershell. Am i right? 

Is there any way you know so i can use powershell to make those changes? 

Thank you in advance. 

Best regards 
Dolph

**Comment by seanmcne** [comment]
This is all in the sitemap.xml for each app. I briefly looked at how to emulate that but since it's just adding that module to the sitemap the best way to accomplish this is by ensuring you're using solution packager to extract and edit artifacts.  To quickly add it (prototyping scenario) there is also the app editor/designer to add it (which can also be done via xml and using powershell but there just isn't a shortcut for it).  

If you do find an elegant way or write something please consider posting it on the Xrm Data Powershell Samples git site. Thanks!
