### ISSUE TITLE
Add-CrmSecurityRoleToUser did not work in latest version

### ISSUE THREAD

**Issue by feng-huang** [seanmcne/Microsoft.Xrm.Data.PowerShell#461]
this code below works in version 2.8.11. but not in versions afterwards.
```powershell
$user = Get-CrmRecord systemuser <id> *
$role = Get-CrmRecord role <id> *
Add-CrmSecurityRoleToUser $user $role
```

**Comment by nfeingold-cerium** [comment]
Had the same issue in 2.8.13. 

What is in GitHub
```powershell
function Add-CrmSecurityRoleToTeam{
# .ExternalHelp Microsoft.Xrm.Data.PowerShell.Help.xml

    [CmdletBinding()]
    PARAM(
        [parameter(Mandatory=$false)]
        [Microsoft.Xrm.Tooling.Connector.CrmServiceClient]$conn,
        [parameter(Mandatory=$true, Position=1, ParameterSetName="CrmRecord")]
        [PSObject]$TeamRecord,
        [parameter(Mandatory=$false, Position=2, ParameterSetName="CrmRecord")]
        [PSObject]$SecurityRoleRecord,
        [parameter(Mandatory=$true, Position=1, ParameterSetName="Id")]
        [string]$TeamId,
        [parameter(Mandatory=$false, Position=2, ParameterSetName="Id")]
        [string]$SecurityRoleId,
        [parameter(Mandatory=$false, Position=2)]
        [string]$SecurityRoleName
    )
}
```

What was downloaded from latest

```powershell
function Add-CrmSecurityRoleToUser{
# .ExternalHelp Microsoft.Xrm.Data.PowerShell.Help.xml

    [CmdletBinding()]
    PARAM(
        [parameter(Mandatory=$false)]
        [Microsoft.Xrm.Tooling.Connector.CrmServiceClient]$conn,
        [parameter(Mandatory=$true, Position=1, ParameterSetName="CrmRecord")]
        [PSObject]$UserRecord,
        [parameter(Mandatory=$false, Position=2, ParameterSetName="CrmRecord")]
        [PSObject]$SecurityRoleRecord,
        [parameter(Mandatory=$true, Position=1, ParameterSetName="Id")]
        [string]$UserId,
        [parameter(Mandatory=$false, Position=2, ParameterSetName="Id")]
        [string]$SecurityRoleId
    )
}
```

**Comment by seanmcne** [comment]
These are two different functions above one is for the user and one is for a team.  What error are you getting or what was expected versus what actually happened?

Thx!

```
$user = "guid"
$role = "guid"
Add-CrmSecurityRoleToUser $user $role
```

or 

```
$user = "guid"
$role = "guid"
Add-CrmSecurityRoleToUser -UserId $user -SecurityRoleId $role
```

**Comment by nfeingold-cerium** [comment]
Apologies- It was the end of a long work day, I missed the difference! That is a non-issue. The issue I was incurring as such,

I was running this code locally:

```powershell
Add-CrmSecurityRoleToUser -conn $CrmConnection -UserId $SystemUserId -SecurityRoleName $Role
```

**Expected** was that the security role be added to the user. 

**Actual** was that I was getting the exceptions that 'SecurityRoleName' param is unknown: `A parameter cannot be found that matches parameter name 'SecurityRoleName'.`

Unfortunately, providing the whole stack trace is misleading, as the error is being thrown from the function calling this, rather than the function itself. Just looking at commit history, nothing has changed in code from previous to now. The only difference is that I am on a new machine, so I just installed the latest package using `Install-Module`. It is possible that this is user error, but I do not believe that is the case. 
Let me know if there is anything else I can provide to help

**Comment by seanmcne** [comment]
No worries :) thanks for clarifying! I just gave this a quick test locally as well just to be sure, I'm not able to repro the issue, can you try to add/remove using the same parameter names?  I typically don't ever pass a connection and just the default $conn variable to keep things simple but I tested with both here and it's working well locally for me at this point. 

Are you downloading from powershell gallery? 

![image](https://user-images.githubusercontent.com/2292260/112048747-bb245e00-8b1c-11eb-9e84-d42006d09327.png)

```
Add-CrmSecurityRoleToUser -conn $conn -UserId (Invoke-CrmWhoAmI).Userid -SecurityRoleName "Salesperson" -Verbose

Remove-CrmSecurityRoleFromUser -conn $conn -UserId (Invoke-CrmWhoAmI).Userid -SecurityRoleName "SalesPerson" -Verbose
```

**Comment by nfeingold-cerium** [comment]
Yes, I installed using `Install-Module Microsoft.Xrm.Data.PowerShell -Force`. I just verified doing a reverse search, and even *just* reinstalled with the same results.

I was able to replicate here:
![image](https://user-images.githubusercontent.com/78935180/112060656-b3fc5080-8b1a-11eb-8d46-6dcdc8743dc4.png)

More info:
![image](https://user-images.githubusercontent.com/78935180/112060975-15bcba80-8b1b-11eb-8895-397e4cd56976.png)

Also, just to let you know, I copied the contents of the command and used them locally, so my work is not currently blocked. As such, I am not *personally* in a rush to get this done, but I am happy to help where I can.

**Comment by OmnipotentOwl** [comment]
@seanmcne, I think this issue looks to be because the code version in GitHub is ahead of the code version in the PowerShell Gallery. I know the fixes put forward for #458, #459 were after the last release made to the gallery and so are unavailable generally. Releasing a new version to the Powershell Gallery I think would resolve the issue in this case.

**Comment by seanmcne** [comment]
Ok, I can reproduce this issue now so I'll see what's going on - thanks for hanging in there with me on this one!

**Comment by seanmcne** [comment]
Release should be live any minute - thanks again! 

https://www.powershellgallery.com/packages/Microsoft.Xrm.Data.Powershell/2.8.14

**Comment by nfeingold-cerium** [comment]
Thanks @seanmcne !
