### ISSUE TITLE
Get-CrmRecordsByFetch Returns Different Representation of Modified On

### ISSUE THREAD

**Issue by CoreySutton** [seanmcne/Microsoft.Xrm.Data.PowerShell#472]
When retrieving records by FetchXML, where a link entity is involved, modified on is not consistently represented. 
- The primary entity modified on is a string, whereas the linked entity modified on is a datetime. 
- The primary entity modified on does not return the seconds component of the datetime, whereas the linked entity does.
- The primary entity modified on is universal time whereas the linked entity modified on is returned in local time

Primary entity
- Entity: CBG
- Field: Modified On
- Type: System.String
- Value: 1/08/2019 11:17 AM

Link entity
- Entity: Person
- Field: Modified On
- Type: System.DateTime
- Value: 5/11/2020 5:46:58 am

Each entity is access via ForEach-Object as follows:
Primary Entiy: `$_.'modifiedon'`
Secondary Entiy: `$_.'person.modifiedon'`

Is this by design, expected, a bug or user error?

**Comment by seanmcne** [comment]
I'd be curious to see if the data in the response (when tracing with something like fiddler) has the same issue or if it's when the parser in our module here is not able to determine if one field is a date when it should be able to (trying to figure out, is this something in the module or is it doing what it should do based on the data coming back)?

**Comment by seanmcne** [comment]
Is it reproducible using Account & Contact with out of the box dates like "CreatedOn" for each entity?  I could help debug it then as well.

**Comment by CoreySutton** [comment]
Yep, replicatable using OOTB fields and entities. I have attached a PS script (as a txt file) that queries account by fetch with a link to contact.

[Debuging.txt](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/files/6658979/Debuging.txt)

The script outputs the following:

Reponse Object 0: @{original=System.Collections.Generic.Dictionary`2[System.String,System.Object]; ReturnProperty_Id=79b1c1bd-89e8-e911-a812-000d3a6aa454; contactlink.modifiedon_Property=[contactlin
k.modifiedon, Microsoft.Xrm.Sdk.AliasedValue]; contactlink.modifiedon=4/11/2020 10:36:34 pm; contactlink.contactid=9c63954f-37ea-e911-a812-000d3a6aacaf; contactlink.createdon_Property=[contactlink.c
reatedon, Microsoft.Xrm.Sdk.AliasedValue]; modifiedon_Property=[modifiedon, 6/10/2019 10:36:40 pm]; EntityReference=Microsoft.Xrm.Sdk.EntityReference; ReturnProperty_EntityName=account; contactlink.
contactid_Property=[contactlink.contactid, Microsoft.Xrm.Sdk.AliasedValue]; createdon_Property=[createdon, 6/10/2019 10:36:40 pm]; accountid_Property=[accountid, 79b1c1bd-89e8-e911-a812-000d3a6aa454
]; modifiedon=7/10/2019 11:36 AM; logicalname=account; accountid=79b1c1bd-89e8-e911-a812-000d3a6aa454; createdon=7/10/2019 11:36 AM; contactlink.createdon=9/10/2019 1:51:36 am}

Primary Enitty ID: 79b1c1bd-89e8-e911-a812-000d3a6aa454
Primary Enitty Modified On: 7/10/2019 11:36 AM
Primary Enitty Modified On Type: System.String

Link Enitty ID: 9c63954f-37ea-e911-a812-000d3a6aacaf
Link Enitty Modified On: 4/11/2020 10:36:34 pm
Link Enitty Modified On Type: System.DateTime

**Comment by kovnojava** [comment]
I've just encountered this problem as well, with both datetime and other types of fields.

It seems that when fetching records using Get-CrmRecordsByFetch with linked entities, all attributes in the primary entity gets "flattened" into string types, whereas the attributes in the linked entities retain their type.

Simplified example:

`<fetch>
  <entity name="entity1" >
    <attribute name="lifecycle" />
    <link-entity name="link" from="link" to="link" link-type="outer" alias="entity2" >
      <attribute name="lifecycle" />
    </link-entity>
  </entity>
</fetch>`

both these "lifecycle" fields are actually picklists.

But when I GetType() on them, the first one (in enitity1) is a string, containing the value that was selected. However, the other one (entity2.lifecycle) returns OptionSetValue.

Using the exact same query in FetchXML Builder in XrmToolbox returns the expected value, so the problem seems related to Get-CrmRecordsByFetch (or some of the underlying code)

**Comment by seanmcne** [comment]
I'm just looking into this now a bit, based on going over how the platform returns data and how it's represented in the module, I have a couple of thoughts for context, but then also a suggestion where you can get access to the underlying object and object values returned: 

**Where are the objects of the data coming from?**
The data coming back in powershell here is from XrmToolings connection [CrmServiceClient.GetEntityDataByFetchSearch()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient.getentitydatabyfetchsearch?view=dynamics-xrmtooling-ce-9).  This returns a dictionary (record collection) of dictionaries (string/object value properties) - Dictionary<String,Dictionary<String,Object>>.  

The property named the same as the field/attribute is a string representation of the object returned (that comes from parseRecordsPage which tries to figure out how best to represent the object value) - this is one spot that might be able to address this issue but we have to be careful as this is used for anything pulling back data. 

**Can you access the original or _raw_ object of the property returned by ServiceClient?**
For scenarios where the raw object is required for special circumstances or things that might have multiple values or metadata it would be necessary to use the underlying object returned from GetEntityDataByFetchSearch, for those scenarios the object returned is stored in the in the 'fieldName'_Property attribute. 

Using the example above, the names would be: 
Primary Entiy: $_.'modifiedon_Property'
Secondary Entiy: $_.'person.modifiedon_Property'

As a second backstop, each record in CrmRecords has an object/property called "original" - this is the same object which is returned by the platform (it was put in as a way to get the original view of what was returned as-is without any assumptions) - looking at the original record it does appear as if the string value does come back from CrmServiceClient which is why we're seeing it as a string in the property value.  However, you also have access to the _Property value which should contain the DateTime object as illustrated here: 
![image](https://user-images.githubusercontent.com/2292260/124666179-43800200-de73-11eb-81a0-d52931a67906.png)


**Potential solution when consuming the data returned**
1. What might help in your script today would be to use the _Property value and determine if it's a DateTime or if it's an aliased value which has an underlying value Type of DateTime. Primary Entiy: ```$_.'modifiedon_Property'.Value``` and Secondary Entity: ```$_.'person.modifiedon_Property'.Value.Value``` _(two Values, because the value of the Property is actually an Xrm.Sdk.AliasedValue which has a value of a DateTime)_.
2. When parsing the record we could inspect each property to see if it has an _Property as well and try to override the property coming out of the platform as a string and turn it into a DateTime value.  Right now parsing the records returned pays a performance penalty and I've been trying to come up with some ways to avoid parsing through each record - going down this path would likely add more overhead. 


Hopefully this information is helpful, the inconsistency is rough however trying to _fix it in post_ might also add some future headaches as it's currently returning what the platform sends back (not necessarily what the end-user might expect) and mainly for link entity scenarios where there's an object buried in another object.

**Comment by seanmcne** [comment]
I'm just looking into this now a bit, based on going over how the platform returns data and how it's represented in the module, I have a couple of thoughts for context, but then also a suggestion where you can get access to the underlying object and object values returned: 

**Where are the objects of the data coming from?**
The data coming back in powershell here is from XrmToolings connection [CrmServiceClient.GetEntityDataByFetchSearch()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient.getentitydatabyfetchsearch?view=dynamics-xrmtooling-ce-9).  This returns a dictionary (record collection) of dictionaries (string/object value properties) - Dictionary<String,Dictionary<String,Object>>.  

The property named the same as the field/attribute is a string representation of the object returned (that comes from parseRecordsPage which tries to figure out how best to represent the object value) - this is one spot that might be able to address this issue but we have to be careful as this is used for anything pulling back data. 

**Can you access the original or _raw_ object of the property returned by ServiceClient?**
For scenarios where the raw object is required for special circumstances or things that might have multiple values or metadata it would be necessary to use the underlying object returned from GetEntityDataByFetchSearch, for those scenarios the object returned is stored in the in the 'fieldName'_Property attribute. 

Using the example above, the names would be: 
Primary Entiy: $_.'modifiedon_Property'
Secondary Entiy: $_.'person.modifiedon_Property'

As a second backstop, each record in CrmRecords has an object/property called "original" - this is the same object which is returned by the platform (it was put in as a way to get the original view of what was returned as-is without any assumptions) - looking at the original record it does appear as if the string value does come back from CrmServiceClient which is why we're seeing it as a string in the property value.  However, you also have access to the _Property value which should contain the DateTime object as illustrated here: 
![image](https://user-images.githubusercontent.com/2292260/124666179-43800200-de73-11eb-81a0-d52931a67906.png)


**Potential solution when consuming the data returned**
1. What might help in your script today would be to use the _Property value and determine if it's a DateTime or if it's an aliased value which has an underlying value Type of DateTime. Primary Entiy: ```$_.'modifiedon_Property'.Value``` and Secondary Entity: ```$_.'person.modifiedon_Property'.Value.Value``` _(two Values, because the value of the Property is actually an Xrm.Sdk.AliasedValue which has a value of a DateTime)_.
2. When parsing the record we could inspect each property to see if it has an _Property as well and try to override the property coming out of the platform as a string and turn it into a DateTime value.  Right now parsing the records returned pays a performance penalty and I've been trying to come up with some ways to avoid parsing through each record - going down this path would likely add more overhead. 


Hopefully this information is helpful, the inconsistency is rough however trying to _fix it in post_ might also add some future headaches as it's currently returning what the platform sends back (not necessarily what the end-user might expect) and mainly for link entity scenarios where there's an object buried in another object.

**Comment by seanmcne** [comment]
I'm just looking into this now a bit - after digging into how the platform returns data and how it's represented in the module, I have a couple of thoughts for context, but then also a suggestion where you can get access to the underlying object and object values returned: 

**Where are the objects of the data coming from?**
The data coming back in powershell here is from XrmToolings connection [CrmServiceClient.GetEntityDataByFetchSearch()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient.getentitydatabyfetchsearch?view=dynamics-xrmtooling-ce-9).  This returns a dictionary (record collection) of dictionaries (string/object value properties) - Dictionary<String,Dictionary<String,Object>>.  

The property named the same as the field/attribute is a string representation of the object returned (that comes from parseRecordsPage which tries to figure out how best to represent the object value) - this is one spot that might be able to address this issue but we have to be careful as this is used for anything pulling back data. 

**Can you access the original or _raw_ object of the property returned by ServiceClient?**
For scenarios where the raw object is required for special circumstances or things that might have multiple values or metadata it would be necessary to use the underlying object returned from GetEntityDataByFetchSearch, for those scenarios the object returned is stored in the in the 'fieldName'_Property attribute. 

Using the example above, the names would be: 
Primary Entiy: $_.'modifiedon_Property'
Secondary Entiy: $_.'person.modifiedon_Property'

As a second backstop, each record in CrmRecords has an object/property called "original" - this is the same object which is returned by the platform (it was put in as a way to get the original view of what was returned as-is without any assumptions) - looking at the original record it does appear as if the string value does come back from CrmServiceClient which is why we're seeing it as a string in the property value.  However, you also have access to the _Property value which should contain the DateTime object as illustrated here: 
![image](https://user-images.githubusercontent.com/2292260/124666179-43800200-de73-11eb-81a0-d52931a67906.png)


**Potential solution when consuming the data returned**
1. What might help in your script today would be to use the _Property value and determine if it's a DateTime or if it's an aliased value which has an underlying value Type of DateTime. Primary Entiy: ```$_.'modifiedon_Property'.Value``` and Secondary Entity: ```$_.'person.modifiedon_Property'.Value.Value``` _(two Values, because the value of the Property is actually an Xrm.Sdk.AliasedValue which has a value of a DateTime)_.
2. When parsing the record we could inspect each property to see if it has an _Property as well and try to override the property coming out of the platform as a string and turn it into a DateTime value.  Right now parsing the records returned pays a performance penalty and I've been trying to come up with some ways to avoid parsing through each record - going down this path would likely add more overhead. 


Hopefully this information is helpful, the inconsistency is rough however trying to _fix it in post_ might also add some future headaches as it's currently returning what the platform sends back (not necessarily what the end-user might expect) and mainly for link entity scenarios where there's an object buried in another object.

**Comment by kovnojava** [comment]
Thank you very much for looking into this and explaining where the problem originates stems from, Sean!

In my current project, I work with a relatively small dataset, which I need to compare to a record stored in another kind of database. For this reason, I have had to curate each record and convert some attribute to different formats, to make sure they can be compared correctly across the two platforms.

So the easy solution for me in this case was to change my curation function to always read from the _Property attribute instead of from the normal attribute. And in case of the linked entities (eg. if type is Xrm.Sdk.AliasedValue), dig one level further down for the value and type.

In this setup, this hardly had any impact on performance, but it would of course be nice if the Get-CrmRecordsByFetch could handle it sometime in the future, to avoid having to write extra functions for it. 

To avoid breaking what others might have created that uses the module, perhaps it could be done by adding an optional switch to Get-CrmRecordsByFetch (-ProperAttributeTypes or similar)

**Comment by seanmcne** [comment]
Thanks for the feedback on this!

I definitely appreciate the frustration around this inconsistency, the reason we had originally added each attributes _"_Property"_ was to enable the script writer to handle problems just like this one, when there are inconsistencies or strange datatype differences but you really just want the _value_ of the object.  This is one of those scenarios where the scenario does a good job of exposing the _inconsistency_ much more directly because the properties are consistent on all entities no matter if it's directly queried on the entity or joined and the result looks different, correct me if I'm wrong but this should be almost identical for any C# or .NET developer doing the same type of interpreting of results from FetchXml. My two primary concerns are: 
1. Where do we stop and start - just known attributes or all?  All aliased values and try to interpret, but when happens if it fails how do we fall back?  This may lead to other inconsistencies. 
2. Performance: today perf takes a solid hit when interpreting the results and this could add more overhead
3. Would documentation be sufficient?  You could share a sample of the out of the box example here out on https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.samples in case anyone runs into the same type of issue? 

For this specific issue, I could look at specific aliased values for specific field names on joined queries through the same method you've used (something we should only do for some system properties).  On the other hand if that's ever 'fixed' or if the design is changed or if the user includes another datetime value in a joined entity there are also inconsistencies we may need to consider addressing.  Ultimately, it may start create some additional confusion.
