### ISSUE TITLE
Use of deployment settings file

### ISSUE THREAD

**Issue by craig-lund** [seanmcne/Microsoft.Xrm.Data.PowerShell#493]
With "Import-crmSolution" be updated to support the use of the Deployment Settings file?

**Comment by seanmcne** [comment]
Can you send a link to documentation of the use of this file?  Thanks!

**Comment by craig-lund** [comment]
https://docs.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools

**Comment by seanmcne** [comment]
Hi Craig, thanks for this info!  I believe this file would be used with the deployment tools and would be complementary to this module but not included (since this module adds a layer on top of the already existing D365/Dataverse Powershell connection - a part of XRM Tooling). If you want to reach out w/ a PM name that would be fine and I can follow up but I didn't think the XRM Powershell connector natively supported a deployment package without using package deployer.  Thanks! 

https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/admin/deploy-packages-using-package-deployer-windows-powershell?view=op-9-1

**Comment by craig-lund** [comment]
Thanks Sean! That makes total sense. I do have the PowerShell that wraps around to perform this function. I know the current deployment tooling that enables this is not working as described. Unless I can get a resolution from the tooling group I will, when I find the time as you know, expand on my custom package deployer (that supports patching) to include this. Thanks for making the time and following up. I know it can be challenging.
