### ISSUE TITLE
Install error started 11/9 afternoon PT

### ISSUE THREAD

**Issue by craig-lund** [seanmcne/Microsoft.Xrm.Data.PowerShell#515]
Hi Sean, since your update 8 days ago here has been 0 downloads. Up until this afternoon it was pulling the previous version. The new version gives me this... 

  PackageManagement\Install-Package : Package 'Microsoft.Xrm.Data.Powershell' failed to be installed because: The file 
  'C:\Users\VssAdministrator\AppData\Local\Temp\xnpxsdr0\[Content_Types].xml' already exists.
  At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
  + ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
  +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : InvalidResult: (Microsoft.Xrm.Data.Powershell:String) [Install-Package], Exception
      + FullyQualifiedErrorId : Package '{0}' failed to be installed because: {1},Microsoft.PowerShell.PackageManagement 
     .Cmdlets.InstallPackage

As a work around I added this to my install line

   Install-Module -Name Microsoft.Xrm.Data.Powershell -RequiredVersion 2.8.14 -Force

**Comment by seanmcne** [comment]
@craig-lund thx for reaching out.  The 0 downloads appears to be a problem with PowerShell Gallery, I've noticed none of my stats are updating, for some reason and I've reached out to the powershell gallery folks to see if they can help figure out why.  

Re: the issue, the problem you're having was with a specific version that was released but subsequently fixed.  
In the process of prepping an alpha/prerelease for the next update, it looks like 2.8.16 was re-listed and 2.8.17 was unlisted which caused the issue you're seeing.  

I've gone in and reset the listed/unlisted state for .16 and made sure .17 is the latest release version. I'm not entirely sure how these were toggled during the releasing and testing of the latest alpha package - I'm going to review my scripts for release as well as double checking in the gallery again to ensure this doesn't happen again.

**Comment by craig-lund** [comment]
@seanmcne thanks for the quick response. I will check and see if the issue is resolved. Much appreciated.

**Comment by seanmcne** [comment]
FYI @craig-lund I'm going to ship an updated module 2.8.19, it's been tested on my end and tested by several folks running into the null issue when zero records are returned.

**Comment by craig-lund** [comment]
Thanks @seanmcne , I will work on validating any issues when we are in our production environment. For stability, I am still grabbing 2.8.14.

**Comment by seanmcne** [comment]
If it helps, here are the issues that occurred between .14 and now .19: 
- Content_Types.xml error - when including the XRM tooling module the content types xml file was erroneously included. Unfortunately, this caused an issue when packaging and publishing the nuget package to PowerShell gallery (tests all worked fine) but when the module was downloaded from the gallery there was a conflict with the included content types file causing imports from the gallery to fail. Removing the erroneously included content_types file, prior to packaging, resolved the issue. 
- Zero records issue, .15-.18 had an issue where a query resulting in zero rows throws a null exception - there weren't any changes to this code path in the module so I suspect the xrm tooling connector slightly changed how it was writing out to the pipeline when there are zero records returned.  I was able to check for null and handle it (this is fixed in .19) 
- While publishing the fix for the above issue as an -alpha or -beta release (pre-release), a previously unlisted release version with the first issue was re-listed on the gallery causing the first issue to arise again - I delisted those modules again on the gallery to ensure they were no longer installable and will be publishing .19 

I'll be publishing .19 shortly which should have all of the above addressed.
