### ISSUE TITLE
Updating gender existing null value with Male value and throws error

### ISSUE THREAD

**Issue by nsksaisaravana** [seanmcne/Microsoft.Xrm.Data.PowerShell#519]
Set-CrmRecord -conn $conn -EntityLogicalName contact -Id "xxxxxxxxxxxxxxxxxx" -Fields @{"gendercode"=1 } 

I am using the above command to set value but it fails 

<img width="688" alt="image" src="https://user-images.githubusercontent.com/17681573/227070468-823bb2ed-cdb8-4012-97e0-8994e2aa685b.png">

**Comment by seanmcne** [comment]
[Gendercode documentation](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/contact#BKMK_GenderCode)

it is a picklist/option set value and will need to be assigned an option set type of value - instead of setting it to an int32 value of 1, assign it the following value which should be of the right type. 

(New-CrmOptionSetValue 1)

**Comment by nsksaisaravana** [comment]
tons of thanks, working fine.
