### ISSUE TITLE
Set-CrmRecordState FaultException messages are getting swalled

### ISSUE THREAD

**Issue by Joseph-Duty-VA** [seanmcne/Microsoft.Xrm.Data.PowerShell#529]
When the Set-CrmRecordState throws a FaultException, that info is not getting returned.  e.g. when I run this command attempting to deactivate a workflow which I know doesn't exist, I get an incomplete exception:

try{Set-CrmRecordState -conn $conn -Id CE9B7BB0-A6D6-463A-A7FB-5036E3FB0788 -EntityLogicalName "workflow" -StateCode 'Inactive' -StatusCode 'Inactive'
} catch { Write-Host "**Unable to Deactivate Record: Exception Type $($_.Exception) and message $($_.Exception.Message**)" -foregroundcolor red -backgroundcolor black
    }

Output is: "Unable to Deactivate Record: Exception Type System.Management.Automation.RuntimeException and message "

As opposed to when I pass in an invalid id, I get the actual error message "Unable to Deactivate Record: Exception Type System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'Id'. Cannot convert value "XXXB7BB0-A6D6-463A-A7FB-5036E3FB0788" "

**Comment by seanmcne** [comment]
Thanks for taking the time to log this @Joseph-Duty-VA, this is quite interesting.  I did a quick test and I think the reason you're not finding the exception is due to the fact the update in XRM Tooling failed but it doesn't return an actual exception and this winds up throwing something that doesn't exist (an exception it expects, but there is no exception to throw), unfortunately the provided status update only returns 'false' when the update fails: https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient.updatestateandstatusforentity?view=dataverse-sdk-latest 

![image](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/assets/2292260/23800146-5e2e-477f-91ca-b2dcbfdd2008)

Using UpdateStateAndStatusForEntity gives us a very simple and reliable way to update the state & status for a given record, however the downside is that it doesn't return a useful error message to the caller.  I believe it does log something to the xrm tooling log, but we only get to see if it's 'true' (success) or 'false' (failure) 

One potential resolution to this would be to specifically throw a new exception, but we don't get any kind of underlying reason.  All of that said, there are only a few, typical, reasons you would get a failure which are: 
- Record with that ID is not found 
- Entity with that name isn't valid for that environment 
- a runtime error (ie: plugin, timeout, database error, etc)


I also mocked up a setstaterequest, just to see what happens when we call that directly 
![image](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/assets/2292260/422d5c8a-b75d-4f87-89c1-af9c6ee100e1)

And we do get back a platform error: 
![image](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/assets/2292260/88b46235-76ac-4fe8-9869-5d52b5cd391a)

This may leave us with three, less than ideal, options: 
1. Leave things as they are and throw a generic failure exception (all we know is 'false' which means something failed) 
2. Dump the use of UpdateStateAndStatusForEntity and switch to setState - there is some technical debt to this as it pertains to future updates which isn't ideal, however UpdateStateAndStatusForEntity does some additional pre-checks before sending the request which might be helpful like translating the status labels (text) to the proper integer/optionset values. Recreating this would require calling ..GetPickListElementFromMetadataEntity('inputEntityname','statecode') and status code, then searching those values to match the input strings, then mapping that value, and then calling setState. If anything fails, return a failure message to the caller and if all passes execute the operation (setState) and return the result or exception. 
3. Have a fallback when UpdateStateAndStatusForEntity fails, fallback to setState but that will require everything for the second option and may behave differently or we have to implement all the checks UpdateStateAndStatusForEntity is already doing.  

Side note: when looking at workflow statuscode and statecode values, I noticed they don't have active, inactive - not sure if that helps you or not but I thought I'd mention it, I don't think passing Inactive for a workflow deactivate it, but curious to know if you've found that to work or not :) 
![image](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/assets/2292260/2809f3d8-8e60-48be-b445-89b341c6ef78)
![image](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/assets/2292260/a342a5f1-a7ee-48af-b83f-72a68733af78)

**Comment by Joseph-Duty-VA** [comment]
Thanks for the analysis and thorough response.  You are correct that "Inactive" is not a valid status or state, and that did turn out to be the bug that originally brought up this finding.  My script now works (changing the values to 'Draft' instead of 'Inactive') when the conditions are correct (aka the workflow does exist).  

On the other note - "it doesn't return a useful error message to the caller. I believe it does log something to the xrm tooling log, but we only get to see if it's 'true' (success) or 'false' (failure)" - this sounds to me like it would be a worthwhile enhancement request for the UpdateStateAndStatusForEntity API.  In my view, true/false as the result of an operation is not helpful unless there is a way to see why it didn't succeed.  I generally believe that less code leads to a better/more maintainable solution, but UpdateStateAndStatusForEntity seems like an incomplete implementation.  In option 2, you seem to be describing recreating the behaviors of the existing API (if I'm following correctly) because it lacks clear messaging.

**Comment by seanmcne** [comment]
I completely agree, I'm not sure if Xrm Tooling accepts feedback via github but I think it would be worth filing feedback for that (we are consuming/using that api here, which is why we're blind to the exception from success or fail).  CrmServiceClient may not get all the same updates or be updated as frequently as dataverseclient, so I'd recommend sharing this feedback on the UpdateStateAndStatusForEntity API in the dataverseclient github (it appears to have the same functionality in dataverseclient still) https://github.com/microsoft/PowerPlatform-DataverseServiceClient
